name: uploadcare_client
description: A dart library for working with Uploadcare REST API. File uploads, media processing, and adaptive delivery for web and mobile.
version: 7.2.0
homepage: https://github.com/KonstantinKai/uploadcare_client
repository: https://github.com/KonstantinKai/uploadcare_client
issue_tracker: https://github.com/KonstantinKai/uploadcare_client/issues

topics:
  - uploadcare
  - file-uploading
  - image-transformations
  - file-analysis
  - file-converting

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  web: ^1.1.1
  http: ^1.6.0
  crypto: ^3.0.7
  meta: ^1.18.1
  mime: ^2.0.0
  http_parser: ^4.1.2
  equatable: ^2.0.8

dev_dependencies:
  test: ^1.25.0
  mockito: ^5.4.4
  lints: ^5.1.0
  build_runner: ^2.4.0
  path: ^1.9.0
  pubspec_extract:
    git:
      url: https://github.com/KonstantinKai/pubspec_extract
      ref: feat/fields-filter
