name: uploadcare_flutter
description: A flutter/dart library for working with Uploadcare REST API. File uploads, media processing, and adaptive delivery for web and mobile.
version: 5.0.2
homepage: https://github.com/KonstantinKai/uploadcare_client
repository: https://github.com/KonstantinKai/uploadcare_client
issue_tracker: https://github.com/KonstantinKai/uploadcare_client/issues

topics:
  - uploadcare
  - file-uploading
  - image-transformations
  - file-analysis
  - file-converting

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  uploadcare_client: ^7.2.1
dev_dependencies:
  flutter_lints: ^1.0.4
  pubspec_extract:
    git:
      url: https://github.com/KonstantinKai/pubspec_extract
      ref: feat/fields-filter

flutter:
  uses-material-design: false
